### ISSUE TITLE
Possibility of using a separate location for src/data

### ISSUE THREAD

**Issue by justchen1369** [skylartaylor/cros-updates#12]
Committing every hour inflates the commits and causes some strange behavior in the code insights graphs:
![image](https://user-images.githubusercontent.com/35386456/81317582-08115a00-905b-11ea-91e0-6fc1a4d92646.png)
![image](https://user-images.githubusercontent.com/35386456/81317631-1495b280-905b-11ea-806c-d76bf9f02ad6.png)
![image](https://user-images.githubusercontent.com/35386456/81317650-1a8b9380-905b-11ea-8d09-c27d4ab6b084.png)
Could we keep the data in a separate location(perhaps in another repo?) and fetch it from the webapp?

**Comment by skylartaylor** [comment]
I could, but it would seriously complicate the CI and build processes, and I don't think it would be worth it. This project isn't serious enough to need to use any code insight data and I don't particularly care about the number of commits.

**Comment by justchen1369** [comment]
makes sense, closing.
