### ISSUE TITLE
my chromebook not shows up

### ISSUE THREAD

**Issue by ifhegon** [skylartaylor/cros-updates#14]
https://imgur.com/a/cR3fKKU

**Comment by skylartaylor** [comment]
What device are you looking for? Chances are it's an end-of-life device which means it does not get updates and therefore isn't included.

**Comment by ifhegon** [comment]
hp chromebook 9000 9900

**Comment by skylartaylor** [comment]
That's too vague of a model to give me exact details, can you follow these instructions and tell me what the text is: 

You can find your board name by going to chrome://version
Look at the line that starts with Platform. That line of text ends with the name you need.

**Comment by ifhegon** [comment]
10895.56.0 (Official Build) stable-channel falco_li

**Comment by skylartaylor** [comment]
Yep, as i suspected! falco_li has been end-of-life since Chrome OS 76, which came out some time ago. Your device no longer receives updates, and as such isn't included in cros.tech.
