### ISSUE TITLE
ASUS Chromebook C423 (coral) showing stable as v72 when stable is actually v86

### ISSUE THREAD

**Issue by SgtBreadStick** [skylartaylor/cros-updates#16]
As shown in the title, the ASUS c423 (coral board) is showing as stable version v72.0.3626.122 (11316), the official/current stable version is actually v86.0.4240.183 (13421).

**Comment by skylartaylor** [comment]
Hi! 

I do see this issue, but unfortunately Google's data source that I pull from is the one reporting the version incorrectly, so they will have to be the one to fix the issue. I'll pass the issue along to someone who may be able to help though!
