### ISSUE TITLE
Add alternate model names for variants of systems

### ISSUE THREAD

**Issue by espoelstra** [skylartaylor/cros-updates#17]
The Dell Latitude 5300 2-in-1 is technically `Arcada` which is a variant of `Sarien`. I found `board: sarien` in the search but `Arcada` didn't return any results even though that is what shows up on the bottom of the boot screen in Developer Mode.

**Comment by skylartaylor** [comment]
Hello!

For whatever reason, Google doesn't serve separate data for that board variant - so I'll need to manually add Arcada. I'll have to do a fair bit of refactoring to add custom data to the site, but I've been working on that anyway so it'll happen eventually!

Thanks for bringing this to my attention 😄
