### ISSUE TITLE
Need to add model numbers

### ISSUE THREAD

**Issue by ghost** [skylartaylor/cros-updates#19]
#You need to add model numbers of devices to the search function
Look, I know you are a little light on work right now, but I have tried to use the model number to search for my device and I turned up empty. **This** is what happens when I try to search model numbers.

![Image of what happens when I try to search with the model number]
(https://user-images.githubusercontent.com/73601639/102111185-e8a98f00-3dea-11eb-84f8-ff6b11fc9f81.png)

**Comment by skylartaylor** [comment]
Hello, 

I'm sorry you're having trouble finding your device. You should use the board name for your device instead — I believe it is octopus, but could be wrong. 

Check by opening `chrome://version` in a browser. Your device name is the word at the end of the "Platform" string. 

Most Chromebook manufacturers are bad at naming their devices uniquely and there is no centralized database for model number data i can easily integrate.
