### ISSUE TITLE
HP ENVY X360 13Z - AY000

### ISSUE THREAD

**Issue by mortezamasumi** [skylartaylor/cros-updates#25]
I recently bought HP envy with RYZEN 3 4000 series CPU, I tried to use zork but it failed to boot to chrome os after brunch
which image should I use?

**Comment by skylartaylor** [comment]
Hello, these Github issues are for problems with http://cros.tech itself. I do not provide support for the Brunch project. You can go to https://github.com/sebanc/brunch#support for help.
