### ISSUE TITLE
API Request

### ISSUE THREAD

**Issue by OctonalXX** [skylartaylor/cros-updates#33]
Can we have an api to get the latest download of recovery images?

**Comment by skylartaylor** [comment]
I have a next-generation version of the site I'm working on now that will have a public-facing API for version data and download URLs for recoveries, but the download will come from Google still. I'm not sure when that'll be completed, I've been procrastinating on it for a while.

**Comment by OctonalXX** [comment]
Thanks
(Add this soon)
