### ISSUE TITLE
cros-updates-serving is now deprecated :((

### ISSUE THREAD

**Issue by alexsch01** [skylartaylor/cros-updates#42]
RIP

**Comment by skylartaylor** [comment]
No worries! The data is now available at https://chromiumdash.appspot.com/serving-builds?deviceCategory=Chrome%20OS as well as a couple other sources, so I'll be able to keep the site up and running! I've been procrastinating getting things migrated though, should probably hurry up on that.

**Comment by skylartaylor** [comment]
Hi! Just wanted to let you know I've finished migrating the site over, so it's good to go going forward! Thanks for your concern and for using cros.tech :)
