### ISSUE TITLE
Most individual device pages do not match table data

### ISSUE THREAD

**Issue by jkibble** [skylartaylor/cros-updates#46]
https://cros.tech/device/atlas, as of this date, says the dev channel is `100.0.4896.13` where the overall table says it is `101.0.4951.13` which is correct. This started a month or two ago

Most (all?) of the device pages which the table lists dev at `101.0.4951.13` actually say  `101.0.4918.0` or `100.0.4896.13`

This affects all channels by the looks of it too

**Comment by skylartaylor** [comment]
You are absolutely correct! My apologies for just now getting around to this, what a serious bug. I'm investigating now while also dealing with some data issues from Google and hopefully I'll have a fix up soon. Thank you for reporting!

**Comment by skylartaylor** [comment]
This issue ended up being caused by some build cache issues on Netlify which I've resolved. Device pages should be getting updated properly again. Thanks again for reporting and for your patience while I resolved it!
