### ISSUE TITLE
Incorrect Information  (e.g. nocturne board, I have version 100.0.4896.133, site says stable is 99.0.4844.57)

### ISSUE THREAD

**Issue by jayfoo2** [skylartaylor/cros-updates#48]
Has this project been abandoned?  The information is incorrect, stale.  Is there a new site that I should use instead.

**Comment by skylartaylor** [comment]
Google is currently serving *wildly* incorrect data on their [website for version data](https://chromiumdash.appspot.com/serving-builds?deviceCategory=Chrome%20OS) which has broken my website. I'm hoping they'll get it fixed soon. In the meantime I'll throw a little warning message up on the site. Thanks for reporting the issue!

**Comment by skylartaylor** [comment]
This issue has been resolved! Thanks for your patience.
