### ISSUE TITLE
Difference between versions in /table view and /device view (specifically board = copano)

### ISSUE THREAD

**Issue by TotesRandomer** [skylartaylor/cros-updates#67]
device view stable = 109.0.5414.125 (Incorrect!)
table view stable = 111.0.5563.71 (Correct!)

**Comment by skylartaylor** [comment]
Thanks for reporting this issue, and apologies for taking so long to get back to you. This was one of many issues with the site, which I fixed by *finally* finishing a re-write of it. The new version is [live now!](https://cros.tech/device/copano/)

**Comment by TotesRandomer** [comment]
Nice work Skylar! Happy to be of some assistance. :D
