### ISSUE TITLE
Site malfunction

### ISSUE THREAD

**Issue by kobester03** [skylartaylor/cros-updates#68]
Site no longer loads search field if accessing the site by going to cros.tech. Links also do not work for the table or home. If I search cros.tech plus whatever code name for the board I'm using I'm able to get to the table and search from there without issue.

**Comment by skylartaylor** [comment]
The site is working fine for me across multiple browsers, devices, and internet connections. Try clearing your cache and cookies for the site, as a few weeks ago I pushed a major redesign that could've broken things for you if you're still loading an old cached version of the site in your browser.

Edited to Add: The fact the pages load fine once you hit a page your browser doesn't have cached is the indicator that's your issue!
