### ISSUE TITLE
reddit: fix sticky header row

### ISSUE THREAD

**Issue by justchen1369** [skylartaylor/cros-updates#7]
https://www.reddit.com/r/chromeos/comments/geatoo/a_new_faster_chrome_os_updates_website_crostech/fpmen6b?utm_source=share&utm_medium=web2x

**Comment by skylartaylor** [comment]
fixed in https://github.com/skylartaylor/cros-updates/commit/c655464a98f27600d4f5f8cd7c2f5ea8584d4fa4
