### ISSUE TITLE
reddit: alphabetical order for devices

### ISSUE THREAD

**Issue by justchen1369** [skylartaylor/cros-updates#8]
https://www.reddit.com/r/chromeos/comments/geatoo/a_new_faster_chrome_os_updates_website_crostech/fpmen6b?utm_source=share&utm_medium=web2x

**Comment by skylartaylor** [comment]
fixed in https://github.com/skylartaylor/cros-updates/commit/2265cc63fb04a0c88728edde60f54862aff72b9d
